### ISSUE TITLE
BigQuery error in mk operation: Dataset 'XXX:XXX_MODELS' already exists.

### ISSUE THREAD

**Issue by BlondelMichael** [GoogleCloudPlatform/cortex-data-foundation#11]
Into cicd.sh, existing dataset check can fail if the dataset is empty (for any reason, ex : all object creation failed in last run).
So script think it can create dataset and the build is fail

```
bq_safe_mk() {
  dataset=$1
  # Ideally, this would work, but bq ignores the location flag
  #exists=$(bq ls -d | grep -w "$dataset")
  #if [ -n "$exists" ]; then
  exists=$(bq query --location=$location --project_id=$project_id_tgt --use_legacy_sql=false "select distinct 'KITTYCORN' from ${dataset}.INFORMATION_SCHEMA.TABLES")
  if [[ "$exists" == *"KITTYCORN"* ]]; then
    echo "Not creating $dataset since it already exists"
  else
    echo "Creating dataset $project_id_tgt:$dataset with location: $location"
    bq --location="$location" mk --dataset "$project_id_tgt:$dataset"
  fi
}
```

**Comment by benschuler** [comment]
Hi @BlondelMichael, are there any open questions remaining on that issue or did the response from @Lsubatin answer your question? If you are facing any errors that are blocking your build, please let us know the details and we can help troubleshoot. Thanks!

**Comment by benschuler** [comment]
Closing this issue as inactive. If there are still open questions, please let us know and we will be happy to assist you.
