### ISSUE TITLE
Unable to Access youtube links - Is it active?

### ISSUE THREAD

**Issue by anish97IND** [GoogleCloudPlatform/cortex-data-foundation#13]
Hi, I was trying to access step by step process for cortex framework mentioned in the Read me file however, I was unable to access it. Is it active?

**Comment by nwipfli** [comment]
Hello Anish, if you mean this [link](https://youtu.be/pxfxOYPQw9E), it is loading and playing on my side. Do you use another link ?

**Comment by anish97IND** [comment]
Hi @nwipfli , I tried the one on the read me and also the link you have posted in the comment, it doesn't seem to working for me. Please could you share the video name, if possible? I will try to make a quick search on youtube.

**Comment by anish97IND** [comment]
I was able to access it on a different device.
