### ISSUE TITLE
Error while deploying the cortex demand sensing

### ISSUE THREAD

**Issue by ilterpehlivan** [GoogleCloudPlatform/cortex-data-foundation#14]
Hi,

I am following the user guide from [demand sensing](https://storage.googleapis.com/cortex-public-documents/Cortex%20Demand%20Sensing%20-%20User%20Guide.pdf) and in the first step while running the docker image as below <br>

`gcloud auth configure-docker gcr.io && \
docker run -it --rm \
marketplace.gcr.io/cortex-public/cortex-demand-sensing:latest`

It is giving the following error from the docker image itself <br>

```
Collecting wcwidth==0.2.5
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting googleapis-common-protos<2.0dev,>=1.56.2
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    googleapis-common-protos<2.0dev,>=1.56.2 from https://files.pythonhosted.org/packages/f0/2a/25d8c1ceedc5af97de37434c9c5e38ce28aaa45960aa2bd7aa215fc420c0/googleapis_common_protos-1.57.0-py2.py3-none-any.whl#sha256=a9f4a1d7f6d9809657b7f1316a1aa527f6664891531bcfcc13b6696e685f443c (from google-api-core[grpc]==2.8.2->-r requirements.txt (line 19))

🛑 Python Virtual Environment initialization failed.
Check Logs from the output above.
```
Please advice

Thanks

**Comment by ilterpehlivan** [comment]
It looks like the image generated in Aug 17 works fine this is the name of the image `gcr.io/cloud-marketplace/cortex-public/cortex-demand-sensing@sha256:2712cfefb8435796f40d67d5e1be4e629bbbe488fcdd33c21ea9ab9b9b9b368d`

**Comment by vladkol** [comment]
@ilterpehlivan Thank you for reporting the issue! 
It has been fixed now. Please try once again with `gcloud auth configure-docker gcr.io && \ docker run -it --rm \ marketplace.gcr.io/cortex-public/cortex-demand-sensing:latest`

**Comment by benschuler** [comment]
@ilterpehlivan I can see you reacted with a thumbs up to the fix, so I assume the error has been resolved and will close this issue now. Feel free to re-open it in case the deployment is still failing.

If you have any further questions, please continue to reach out to us and we will be happy to assist :slightly_smiling_face:
