### ISSUE TITLE
Wrong ERD PDF for ECC and/or S/4

### ISSUE THREAD

**Issue by rmphd** [GoogleCloudPlatform/cortex-data-foundation#16]
The ERD PDFs look identical for SAP ECC and SAP S/4, both in the link and in the directory with PDFs.

**Comment by benschuler** [comment]
Hi @rmphd , Thanks for flagging this. You are right, the link for the ECC ERD PDF points to the S/4 file. We will take a look at this and provide an update soon. In the meantime, you can see the correct file by navigating to the `docs/` folder and clicking on the `erd_ecc.pdf` file --> https://github.com/GoogleCloudPlatform/cortex-data-foundation/blob/main/docs/erd_ecc.pdf

**Comment by Cyclenerd** [comment]
I fixed that quickly and created a pull request.
