### ISSUE TITLE
gcloud build command fails when location is eu and parameter is not populated

### ISSUE THREAD

**Issue by benschuler** [GoogleCloudPlatform/cortex-data-foundation#2]
Running the gcloud build command linked here (https://github.com/GoogleCloudPlatform/cortex-data-foundation#execute-the-build) is throwing errors if the BQ datasets are placed in EU region and the gcloud build command does not have the parameter for `_LOCATION=EU`. The documentation lists this as an optional parameter but it makes no mention that it must be provided if datasets are not located in the US (I assume this is the default?).

The error message was:
```
...
Step #0: BigQuery error in load operation: Not found: Dataset cortex-godemos-
Step #0: project:1_SAP_REPLICATED
...
```

**Comment by MaBr84** [comment]
This issue is still happening.

**Comment by benschuler** [comment]
Hi @MaBr84, we have marked this issue as closed a while ago and have had a number of enhancements and fixes that went into the Cortex Data Foundation. If you are getting error messages while deploying, can I please ask you to open a new issue and provide us with details on your deployment parameters as well as the error messages you are seeing? That way we can focus on your specific deployment and help you sort out what is going on.

**Comment by MaBr84** [comment]
Ok thanks, at the moment we're trying a workaround by specifying all the parameters as substitution instead of using the config file.
