### ISSUE TITLE
INVALID_ARGUMENT: invalid build: invalid .substitutions field: substitution key "TEST_DATA" does not respect format "^_[A-Z0-9_]+$" and is not an overridable built-in substitutions

### ISSUE THREAD

**Issue by kevinzhang8888** [GoogleCloudPlatform/cortex-data-foundation#21]
follow the deployment instruction get the following error:gcloud builds submit --project psosap-demo-343019 --substitutions _PJID_SRC=psosap-demo-343019,_PJID_TGT=psosap-demo-343019,_DS_CDC=SAP_CDC_PROCESSED,_DS_RAW=SAP_RAW,_DS_REPORTING=SAP_REPORTING,_DS_MODELS=SAP_MODELS,_GCS_BUCKET=psosap-demo-343019-logs,_TGT_BUCKET=psosap-demo-343019-dags,TEST_DATA=false,_DEPLOY_CDC=true,_GEN_EXT=true,_DEPLOY_SAP=true,_DEPLOY_SFDC=true
Creating temporary tarball archive of 510 file(s) totalling 12.7 MiB before compression.
Some files were not included in the source upload.

Check the gcloud log [/tmp/tmp.gTIXnunYaM/logs/2023.03.03/19.13.52.025345.log] to see which files and the contents of the
default gcloudignore file used (see `$ gcloud topic gcloudignore` to learn
more).

Uploading tarball of [.] to [gs://psosap-demo-343019_cloudbuild/source/1677870832.127254-795084ef66cf4cf1974a4bb0af0fb248.tgz]
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid .substitutions field: substitution key "TEST_DATA" does not respect format "^_[A-Z0-9_]+$" and is not an overridable built-in substitutions

**Comment by benschuler** [comment]
Hi @kevinzhang8888, please note that substitution parameters need to start with a `_` character, so in your case you need to use `_TEST_DATA` instead of `TEST_DATA` and then the deployment should not produce the error any more.

**Comment by kevinzhang8888** [comment]
Thank you, that explains.
