### ISSUE TITLE
DAGS file execution explaination.

### ISSUE THREAD

**Issue by vishvas-chauhan** [GoogleCloudPlatform/cortex-data-foundation#23]
I am successfully able to test the SAP data CDC tables but I would like to know to create those CDC, where are you executing the DAGs, I don't have airflow active env in my cloud shell. So where exactly ?

**Comment by benschuler** [comment]
Hi @vishvas-chauhan, 
The DAGs can be executed in a Cloud Composer environment that needs to be created in your project. Once your Composer instance is available, you can copy the created script files into the DAG bucket of the Composer instance by [following these steps here](https://github.com/GoogleCloudPlatform/cortex-data-foundation#move-the-files-into-the-dag-bucket).
You can find details details on how to [create a Composer instance in Google Cloud's public documentation](https://cloud.google.com/composer/docs/how-to/managing/creating).

Please note the [section about Cloud Composer settings](https://github.com/GoogleCloudPlatform/cortex-data-foundation#gathering-cloud-composer-settings) in our README file as well to make sure the scripts are working properly with all required parameters and connections configured.

**Comment by benschuler** [comment]
Closing this issue as resolved. If there are still open questions, please let us know and we will be happy to assist you.
