### ISSUE TITLE
Recordstamp is expected in raw layer for some reporting views

### ISSUE THREAD

**Issue by chodankarcc** [GoogleCloudPlatform/cortex-data-foundation#25]
Team,
Please note that we are using CDF SLT for data ingestion to BQ RAW layer (table "vbap" and "lips" ) which doesn't contain 'Recordstamp' column.
Hence cortex framework execution fails while creating some reporting views like 'OneTouchOrder', 'OrderToCash'.  Please use case 44099919 for tracking and more information. Hoping for quick fix.

**Comment by benschuler** [comment]
Hi @chodankarcc,
Since the SDF SLT plugin already takes care of the CDC processing before landing the data into BigQuery, you don't need the RAW dataset, but you can configure CDF to land data directly into the CDC dataset instead. Please let me know if this approach resolves your issue.

**Comment by chodankarcc** [comment]
Yes, that we are aware of. What I meant is as CDF brings realtime data to BQ; raw and CDC layer is same. But when we execute cortex framework with deployCDC='false' there are above mentioned reporting views provided by cortex still looks for RECORDSTAMP column while creating views and deployment fails. 
Ex. link for erroneous code: https://github.com/GoogleCloudPlatform/cortex-reporting/blob/f2addbcca5d2f97ad1f4192e406b1249341bde9f/s4/OneTouchOrder.sql
https://github.com/GoogleCloudPlatform/cortex-reporting/blob/f2addbcca5d2f97ad1f4192e406b1249341bde9f/s4/OrderToCash.sql

**Comment by benschuler** [comment]
Oh, I see what you mean now, thanks for clarifying. In this case, the logic that we provide to identify the one touch orders will not work as intended because there is no information about any updates to the entries related to a single order (since the recordstamp and operation flags are missing).
Just to clarify, it is only these two views that are failing, the rest of the deployment has executed fine and you can see the other reporting views in your BigQuery project?
If you want to use the OrderToCash view, my suggestion would be to remove the part at the beginning that references the OneTouchOrder and also remove the two rows where this table is referenced further down, as well as the join statement on this table. This should get rid of your errors during deployment and you can use the remaining KPIs that the view provides.

**Comment by chodankarcc** [comment]
Thanks for reply and acknowledging issue. Here are my comments:

- We found view/build failures only for those two views. 
- As a temporary work around we added current_timestamp as RECORDSTAMP and ran cortex build again it got succeed. 
- We are not sure on much dependencies between cortex reporting views. What we want is to make use of looker 'operational dashboards' on top of cortex looker views.
- Considering above requirement, can you confirm if our workaround is ok to use it? 
- When do you think actual fix will be available in Cortex data foundation release?

**Comment by Lsubatin** [comment]
Hi @chodankarcc - The right workaround would be to either comment those KPIs for One Touch Order out, or replicate table CDPOS and rebuild them to tap CDPOS instead. Those views intentionally rely on RAW datasets with append-only history, if the history cannot  be provided, then I'd recommend commenting those out for your implementation.  You'd also remove them from display in the Looker blocks for operational reporting.

There will be a more explicit callout about this in the ERD in the next minor release as part of the documentation on limitations of merging data on landing for scenarios like this one.

**Comment by Lsubatin** [comment]
hi @chodankarcc , you can comment out https://github.com/GoogleCloudPlatform/cortex-reporting/blob/main/s4/OrderToCash.sql#L227-L232 and https://github.com/GoogleCloudPlatform/cortex-reporting/blob/main/s4/OrderToCash.sql#L88-L89. Also remove OneTouchOrder.sql from [dependencies_s4.txt](https://github.com/GoogleCloudPlatform/cortex-reporting/blob/2af5defb3156d5de883cfe9577281ee8be97c5a2/dependencies_s4.txt#L65) so it does not attempt to deploy the view at all. I suggest you flag these changes with a tag of your own in your fork so they are visible in future upgrades (see [upgrade recommendations](https://github.com/GoogleCloudPlatform/cortex-data-foundation/blob/main/docs/upgrade_recommendations/upgrade_recommendations.md) )

Similarly, I'd remove the lkml view for OneToucheOrder altogether and references in models in Looker. A repo search will point you to them: https://github.com/looker-open-source/block-cortex-sap/search?q=one_touch_order

**Comment by chodankarcc** [comment]
Hello @Lsubatin , With above changes and with Cortex 4.2 build fails (CDC=false) saying 'bstaus_sg not found inside StockMonthlySnapshots' (raw layer), I see table 'stock_monthly_snapshots' is getting created (without bstaus_sg  column) at start of execution and later(after 1.5-2 hr) while creating StockMonthlySnapshots reporting view it fails. Just before this view creation, I see it has stock_monthly_snapshots DDL creation code with bstaus_sg  column but it doesn't replace table. Please have a look at it and fix it.
