### ISSUE TITLE
Encounter invalidArgument in automl-forecasting-training-job while running submit pipeline for demand sensing pipeline

### ISSUE THREAD

**Issue by themaos** [GoogleCloudPlatform/cortex-data-foundation#27]
Hi, I encounterd the following an invalidarugment error message while running the submit_pipeline.py for the demand sensing pipeline. May I know is there any way to workaround or any solution to resolve the error?

Do let me know if more information is required. Thanks! 

_Command Executed_:
python3 src/submit_pipeline.py \
--model-command train_score \
--region us-central1 \
--bigquery-location US \
--pipeline-bucket <pipeline_bucket> \
--vertex-ai-dataset <ai_dataset> \
--vertex-ai-sa <service_account> \
--source-project <project_id> \
--target-project <project_id> \
--target-reporting-dataset <reporting_dataset> \
--cdc-processed-dataset <cdc_dataset> \
--forecast-horizon-weeks 14 \
--context-window-weeks 52 \
--training-node-hours 1

_Errors Encountered:_
google.api_core.exceptions.InvalidArgument: 400 List of found errors: 1.Field: training_pipeline.model_to_upload.labels; Message: There can be no more than 64 labels attached to a single resource. Label keys and values can only contain lowercase letters, numbers, dashes and underscores. Label keys must start with a letter or number, must be less than 64 characters in length, and must be less that 128 bytes in length when encoded in UTF-8. Label values must be less than 64 characters in length, and must be less that 128 bytes in length when encoded in UTF-8.

**Comment by themaos** [comment]
If it helps, i'm following the steps from the [documentation](https://storage.googleapis.com/cortex-public-documents/Cortex%20Demand%20Sensing%20-%20User%20Guide.pdf)

**Comment by themaos** [comment]
Hi @vladkol,

Thanks for the prompt response. I encountered the issue in the **automl-forecasting-training-job** step. 
I also tried setting the _--model-command train_ and encountered the same issue in the **automl-forecasting-training-job-2** step

Attached the logs I extracted from the log explorer. Do let me know if there is any other logs that I might need to extract. Thanks!
[downloaded-logs-20230505-092737.log](https://github.com/GoogleCloudPlatform/cortex-data-foundation/files/11402741/downloaded-logs-20230505-092737.log)

**Comment by themaos** [comment]
Hi @vladkol,

Just wondering is there any possible findings from the log?

**Comment by vladkol** [comment]
Hi @themaos, 
I was not able to reproduce the issue. Please help me troubleshoot it a bit further.
In your source project, there should be a cloud source repository `cortex-demand-sensing`. You should be able to find it in [your cloud source repositories](https://source.cloud.google.com/). 

Please clone the repo, and open `src/forecasting_pipeline.py`. Line 127 is where we pass a relatively short label to the model to be assigned after the training is done. Please remove the `model_labels` argument from that call. 
<img width="585" alt="image" src="https://github.com/GoogleCloudPlatform/cortex-data-foundation/assets/4735184/992657a7-b7b9-44c0-9632-45233b717bc0">

Once it's removed, run `src/submit_pipeline.py` as described in section 4.1 of the [user guide](https://storage.googleapis.com/cortex-public-documents/Cortex%20Demand%20Sensing%20-%20User%20Guide.pdf): 
"How to Train the model".

My suspicion is that your project might have certain policies that automatically assign labels to resources, and the result model ends up with too many/long labels assigned.
Please let me know if it helps. Thanks!

**Comment by themaos** [comment]
Hi @vladkol ,

That does the trick 🤩 
I removed the `model_labels` from `src/forecasting_pipeline.py` and the training was able to proceed.

Thanks so much for the help. 😁

---

In case anybody also encounter similar situation, I also have to modify the `model_labels` codes from `src/models.py` under `get_model` and `evaluate_model` methods since I am not setting it anymore. This will allow the pipeline to run the subsequent steps (ie. `condition-model-exist` steps)

<img width="320" alt="image" src="https://github.com/GoogleCloudPlatform/cortex-data-foundation/assets/97230449/8cd96d42-5803-4998-a28d-a871a16ea09c">
