### ISSUE TITLE
AutoMLForecastingTrainingJob Stuck on Cortex Data

### ISSUE THREAD

**Issue by ab-kotecha** [GoogleCloudPlatform/cortex-data-foundation#42]
I am getting repetitive errors for the VertexAI pipeline running while running it on the Cortex dataset as suggested by various Looker/GCP-linked Cortex frameworks.

Is the error an expected log item of the vertex ai pipeline running? Can someone help me with what is going wrong here? I tried multiple trial and error methods like giving full permission to the service account executing the job, removing any budget limit, and enabling all API services. Still, nothing seems to be working in my favour even after waiting for 2 hours to let it go to the next state. I did try the same workload more than twice with the same step as per Google, but I had the same issue.

[
  {
    "textPayload": "Waiting for job to be provisioned.",
    "insertId": "1lpygqldc71g",
    "resource": {
      "type": "ml_job",
      "labels": {
        "task_name": "service",
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T15:55:41.256638588Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/endpoint": "",
      "ml.googleapis.com/job_state": "QUEUED"
    },
    "logName": "projects/xpl-demo/logs/ml.googleapis.com%2F3440268323059662848",
    "receiveTimestamp": "2023-11-03T15:55:42.094715726Z"
  },
  {
    "textPayload": "Waiting for training program to start.",
    "insertId": "1lpygqldc71l",
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "task_name": "service",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T15:55:41.522460885Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/endpoint": ""
    },
    "logName": "projects/xpl-demo/logs/ml.googleapis.com%2F3440268323059662848",
    "receiveTimestamp": "2023-11-03T15:55:42.094715726Z"
  },
  {
    "textPayload": "Job is preparing.",
    "insertId": "1lpygqldc71x",
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "task_name": "service",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T15:55:43.063241877Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/job_state": "PREPARING",
      "ml.googleapis.com/endpoint": ""
    },
    "logName": "projects/xpl-demo/logs/ml.googleapis.com%2F3440268323059662848",
    "receiveTimestamp": "2023-11-03T15:55:44.093730768Z"
  },
  {
    "textPayload": "Job is running.",
    "insertId": "1lpygqldc740",
    "resource": {
      "type": "ml_job",
      "labels": {
        "task_name": "service",
        "project_id": "xpl-demo",
        "job_id": "3440268323059662848"
      }
    },
    "timestamp": "2023-11-03T15:55:53.721645995Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/job_state": "RUNNING",
      "ml.googleapis.com/endpoint": ""
    },
    "logName": "projects/xpl-demo/logs/ml.googleapis.com%2F3440268323059662848",
    "receiveTimestamp": "2023-11-03T15:55:54.097068817Z"
  },
  {
    "insertId": "z965kbf3n2t6b",
    "jsonPayload": {
      "levelname": "INFO",
      "message": "INFO:google.cloud.aiplatform.training_jobs:No dataset split provided. The service will use a default split."
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0"
      }
    },
    "timestamp": "2023-11-03T15:55:55.497201604Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/trial_type": "",
      "ml.googleapis.com/tpu_worker_id": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  {
    "insertId": "z965kbf3n2t6c",
    "jsonPayload": {
      "levelname": "INFO",
      "message": "INFO:google.cloud.aiplatform.training_jobs:View Training:"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "task_name": "workerpool0-0",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T15:55:55.721984944Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/tpu_worker_id": "",
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/trial_type": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  **{
    "insertId": "z965kbf3n2t6d",
    "jsonPayload": {
      "message": "https://console.cloud.google.com/ai/platform/locations/us-central1/training/398931199701024768?project=515609978228",
      "levelname": "ERROR"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo"
      }
    },**
    "timestamp": "2023-11-03T15:55:55.722064327Z",
    "severity": "ERROR",
    "labels": {
      "ml.googleapis.com/trial_id": "",
      "ml.googleapis.com/tpu_worker_id": "",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_id": "5828173493139188726"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  {
    "insertId": "z965kbf3n2t6e",
    "jsonPayload": {
      "levelname": "INFO",
      "message": "INFO:google.cloud.aiplatform.training_jobs:AutoMLForecastingTrainingJob projects/515609978228/locations/us-central1/trainingPipelines/398931199701024768 current state:"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848"
      }
    },
    "timestamp": "2023-11-03T15:56:00.860888959Z",
    "severity": "INFO",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_type": "",
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/trial_id": "",
      "ml.googleapis.com/job_id/log_area": "root"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  {
    "insertId": "z965kbf3n2t6f",
    "jsonPayload": {
      "levelname": "ERROR",
      "message": "PipelineState.PIPELINE_STATE_RUNNING"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "project_id": "xpl-demo",
        "job_id": "3440268323059662848",
        "task_name": "workerpool0-0"
      }
    },
    "timestamp": "2023-11-03T15:56:00.860950596Z",
    "severity": "ERROR",
    "labels": {
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_id": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  {
    "insertId": "z965kbf3n2t6g",
    "jsonPayload": {
      "message": "INFO:google.cloud.aiplatform.training_jobs:AutoMLForecastingTrainingJob projects/515609978228/locations/us-central1/trainingPipelines/398931199701024768 current state:",
      "levelname": "INFO"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848"
      }
    },
    "timestamp": "2023-11-03T15:56:11.014859567Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/job_id/log_area": "root",
      "ml.googleapis.com/tpu_worker_id": "",
      "ml.googleapis.com/trial_type": "",
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "compute.googleapis.com/zone": "us-central1-a"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  {
    "insertId": "z965kbf3n2t6h",
    "jsonPayload": {
      "levelname": "ERROR",
      "message": "PipelineState.PIPELINE_STATE_RUNNING"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848"
      }
    },
    "timestamp": "2023-11-03T15:56:11.014918357Z",
    "severity": "ERROR",
    "labels": {
      "ml.googleapis.com/tpu_worker_id": "",
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "compute.googleapis.com/zone": "us-central1-a",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_id": "",
      "ml.googleapis.com/trial_type": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:28.694571493Z"
  },
  {
    "insertId": "1a25d3vf403sri",
    "jsonPayload": {
      "message": "INFO:google.cloud.aiplatform.training_jobs:AutoMLForecastingTrainingJob projects/515609978228/locations/us-central1/trainingPipelines/398931199701024768 current state:",
      "levelname": "INFO"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "task_name": "workerpool0-0",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T15:56:31.485451387Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/tpu_worker_id": "",
      "ml.googleapis.com/job_id/log_area": "root"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:34.800640202Z"
  },
  {
    "insertId": "1a25d3vf403srj",
    "jsonPayload": {
      "message": "PipelineState.PIPELINE_STATE_RUNNING",
      "levelname": "ERROR"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "project_id": "xpl-demo",
        "job_id": "3440268323059662848",
        "task_name": "workerpool0-0"
      }
    },
    "timestamp": "2023-11-03T15:56:31.485484140Z",
    "severity": "ERROR",
    "labels": {
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/job_id/log_area": "root"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:56:34.800640202Z"
  },
  {
    "insertId": "1wt7jiif14irvi",
    "jsonPayload": {
      "message": "INFO:google.cloud.aiplatform.training_jobs:AutoMLForecastingTrainingJob projects/515609978228/locations/us-central1/trainingPipelines/398931199701024768 current state:",
      "levelname": "INFO"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T15:57:12.054239631Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/trial_id": "",
      "ml.googleapis.com/job_id/log_area": "root"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:57:15.932174213Z"
  },
  {
    **"insertId": "1wt7jiif14irvj",
    "jsonPayload": {
      "message": "PipelineState.PIPELINE_STATE_RUNNING",
      "levelname": "ERROR"
    },**
    "resource": {
      "type": "ml_job",
      "labels": {
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848"
      }
    },
    "timestamp": "2023-11-03T15:57:12.054299282Z",
    "severity": "ERROR",
    "labels": {
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/job_id/log_area": "root",
      "ml.googleapis.com/tpu_worker_id": "",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/zone": "us-central1-a"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:57:15.932174213Z"
  },
  {
    "insertId": "l3cun8f13axwx",
    "jsonPayload": {
      "levelname": "INFO",
      "message": "INFO:google.cloud.aiplatform.training_jobs:AutoMLForecastingTrainingJob projects/515609978228/locations/us-central1/trainingPipelines/398931199701024768 current state:"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "task_name": "workerpool0-0",
        "project_id": "xpl-demo",
        "job_id": "3440268323059662848"
      }
    },
    "timestamp": "2023-11-03T15:58:33.228556372Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/trial_id": "",
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/trial_type": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:58:35.124071426Z"
  },
  {
    "insertId": "l3cun8f13axwy",
    "jsonPayload": {
      "message": "PipelineState.PIPELINE_STATE_RUNNING",
      "levelname": "ERROR"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0"
      }
    },
    "timestamp": "2023-11-03T15:58:33.228764715Z",
    "severity": "ERROR",
    "labels": {
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/job_id/log_area": "root",
      "ml.googleapis.com/trial_id": "",
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/zone": "us-central1-a"
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T15:58:35.124071426Z"
  },
  {
    "insertId": "3vyybbf1rsj1o",
    "jsonPayload": {
      "message": "INFO:google.cloud.aiplatform.training_jobs:AutoMLForecastingTrainingJob projects/515609978228/locations/us-central1/trainingPipelines/398931199701024768 current state:",
      "levelname": "INFO"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo",
        "task_name": "workerpool0-0"
      }
    },
    "timestamp": "2023-11-03T16:01:15.424869008Z",
    "severity": "INFO",
    "labels": {
      "ml.googleapis.com/trial_type": "",
      "ml.googleapis.com/tpu_worker_id": "",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "compute.googleapis.com/zone": "us-central1-a",
      "ml.googleapis.com/job_id/log_area": "root",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/trial_id": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T16:01:17.274607246Z"
  },
  {
    "insertId": "3vyybbf1rsj1p",
    "jsonPayload": {
      "message": "PipelineState.PIPELINE_STATE_RUNNING",
      "levelname": "ERROR"
    },
    "resource": {
      "type": "ml_job",
      "labels": {
        "task_name": "workerpool0-0",
        "job_id": "3440268323059662848",
        "project_id": "xpl-demo"
      }
    },
    "timestamp": "2023-11-03T16:01:15.424922340Z",
    "severity": "ERROR",
    "labels": {
      "ml.googleapis.com/trial_id": "",
      "compute.googleapis.com/resource_name": "gke-cml-1103-154207--e2-standard-4-43-1cb43fc2-886b",
      "ml.googleapis.com/job_id/log_area": "root",
      "ml.googleapis.com/trial_type": "",
      "compute.googleapis.com/zone": "us-central1-a",
      "compute.googleapis.com/resource_id": "5828173493139188726",
      "ml.googleapis.com/tpu_worker_id": ""
    },
    "logName": "projects/xpl-demo/logs/workerpool0-0",
    "receiveTimestamp": "2023-11-03T16:01:17.274607246Z"
  }
]

**Comment by benschuler** [comment]
Hi @ab-kotecha, thanks for reaching out with this issue. Our team has taken a look at the information provided and there does not seem to be anything related to the samples that we are providing, but rather some general errors related to Vertex AI. Therefore, can you please reach out to the responsible team via the regular Google Cloud support processes, since they will be able to look into more details and suggest potential solutions for this behavior. Feel free to reach out to us again if you have more information to share that indicates that this is related to our content and we will take another look.

**Comment by ab-kotecha** [comment]
The error didn't affect the overall pipeline and outcome. The pipeline stayed on for about 3 hours instead of the claimed one hour in one of the documents from Google Developer Advocate. That made me nervous with this error. Anyway, thanks for your reply. As I tested, we can safely ignore these errors.
