### ISSUE TITLE
Permission Denied Error when Executing deploy.sh Script

### ISSUE THREAD

**Issue by jlopez798** [GoogleCloudPlatform/cortex-data-foundation#48]
I was deploying the project to Google Cloud Build but I got this error:

![image](https://github.com/GoogleCloudPlatform/cortex-data-foundation/assets/12473846/e5365536-930a-4420-b73b-fa12665d2e80)

but this error occurs at every step when a .sh needs to be run, I was trying to add `chmod +x ./src/common/materializer/deploy.sh` 
permission, add an absolute path, deploy in cloud shell, local, and a VM, and other stuff. 
The only way I had a good deployment was with the interactive screen.
can help me?.

The error is reproduced in different steps such as:

- cloudbuild.reporting.yaml
![image](https://github.com/GoogleCloudPlatform/cortex-data-foundation/assets/12473846/e206c0f7-1735-454e-8c35-d91a69a99f98)

- deploy_k9.py / k9_deployer.py
![image](https://github.com/GoogleCloudPlatform/cortex-data-foundation/assets/12473846/5057ade5-5187-495f-b330-cfb60f56643a)

**Comment by TXZebra** [comment]
HI @jlopez798 can you please send an email to cortex-support@google.com with this information?

Thank you!
