### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by agcopley** [GoogleCloudPlatform/cortex-data-foundation#64]
Hello,
Would it be possible to have some clearer documentation on the use of the inventory update sql scripts?
Its not at all clear how and in which order the scripts in inventory_snapshots should be used and with what frequency

Thx

**Comment by agcopley** [comment]
Bump

**Comment by TXZebra** [comment]
Hi @agcopley , could you please reach out to cortex-support@google.com? Our support team can then take a look at this. Thank you!

**Comment by benschuler** [comment]
Hi @agcopley, since we have moved the conversation to the email thread, I'm going to close this issue here. Feel free to reach out if there are any further questions on this.
